apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: YOUR_DEPLOYMENT_NAME_CHANGE_ME
  namespace: spring-labs
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: YOUR_DEPLOYMENT_NAME_CHANGE_ME
            image: 12345678998.dkr.ecr.us-west-2.amazonaws.com/YOUR_REPO_NAME:${IMAGE_TAG}
          restartPolicy: OnFailure
