apiVersion: v1
kind: Service
metadata:
  name: fastapi-app
  namespace: fast-api-ns
  labels:
    app: fastapi-celery
spec:
  selector:
    app: fastapi-celery
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: fastapi-app
  namespace: fast-api-ns
  labels:
    app: fastapi-celery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-celery
  template:
    metadata:
      labels:
        app: fastapi-celery
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: web-app
        image: 185738856137.dkr.ecr.ap-south-1.amazonaws.com/rahulecr95:da994ed67d5e99120ff1dc439476afee80cb0caa
        ports:
        - containerPort: 80
