apiVersion: client.authentication.k8s.io/v1alpha1
kind: Deployment
metadata:
  name: fastapi-celery
  labels:
    app: fastapi-celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-celery
  template:
    metadata:
      labels:
        app: fastapi-celery
    spec:
      containers:
        - name: fastapi-celery
          image: sudhanshu95/fastapi-celery:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
