apiVersion: apps/v1
kind: Deployment
metadata:
  name: sudhanshu95
  labels:
    app: sudhanshu95
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sudhanshu95
  template:
    metadata:
      labels:
        app: sudhanshu95
    spec:
      containers:
        - name: sudhanshu95
          image: sudhanshu95/fastapi-celery:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
