name: CI/CD for FastAPI on EKS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github_credintials
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubernetes context
      run: |
        mkdir -p ~/.kube
        echo ${{ secrets.KUBECONFIG_FILE }} | base64 --decode > ~/.kube/config


    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Build and Push Docker Image
      run: |
        docker build -t your-docker-repo/your-app:latest .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push sudhanshu95/fastapi-celery:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EKS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EKS_HOST }}
        username: ${{ secrets.EKS_USERNAME }}
        key: ${{ secrets.EKS_SSH_KEY }}
        script: |
          kubectl apply -f k8s/git-deployment.yml  # Replace with your Kubernetes deployment YAML file
          kubectl apply -f k8s/your-app-service.yaml  # Replace with your Kubernetes service YAML file
