name: Deploy to EKS
on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Authenticate with Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: 185738856137.dkr.ecr.ap-south-1.amazonaws.com/rahulecr95

      - name: Deploy to Amazon EKS
        run: |
          kubectl apply -f git-deployment.yml
